### ISSUE TITLE
Запрос обрабатывается. 

### ISSUE THREAD

**Issue by altax** [vladislav-puzyrev/vk_spamer_online#1]
@vladislav-puzyrev  Вообще интересная хрень, надеюсь найдет больше пользователей. Но у меня не выходит зафлудить беседу, в логе пишется "запрос обрабатывается" и Больше ничего.

Есть возможность пофиксить? У меня выбрана функция "показывать капчу", так на всякий.

**Comment by vladislav-puzyrev** [comment]
Здравствуй, @altax ! Если я правильно понял, то проблема может быть с ограничением запросов.

Дело в том что спамер использует прокси сервер - https://cors-anywhere.herokuapp.com/ для того чтобы обходить CORS политику браузера, а этот сервер ограничивает количество запросов 200/час, но для спамера это очень мало.

Я клонировал их репозиторий и залил этот прокси сервер на heroku, сейчас ограничений быть не должно! Кстати не работать должны были не только беседы, а вообще всё. Помогло?

**Comment by altax** [comment]
@vladislav-puzyrev что-то все равно не получается, пишет также

![Screenshot_20200427-164110](https://user-images.githubusercontent.com/19414112/80379137-57f76080-88a6-11ea-9241-71a0a498808e.png)

**Comment by vladislav-puzyrev** [comment]
@altax и это именно только с беседами?

**Comment by altax** [comment]
> @altax и это именно только с беседами?

Почему-то уведомления не пришло об ответе.

Сейчас проверил с личными сообщениями, тоже не работает, вечная обработка запроса.  В качестве id использовал кастомный id.

**Comment by altax** [comment]
Так, стоп. Все заработало, когда я изменил текст сообщения. Есть ли какие нибудь ограничения символов?

**Comment by altax** [comment]
В общем, все отлично работает  ( даже удивлен). Моя проблема была в том, что я использовал много символов в тексте. Сейчас проверил, вечная обработка начинается, если количество символов в тексте больше 758, по крайней мере у меня так. В принципе, больше и не надо :)

Спасибо за отличное приложение, все таки есть норм репозитории на гитхабе.

**Comment by vladislav-puzyrev** [comment]
Отлично! Я добавил обработку этой ошибки, теперь она выводится в консоль и если что будет понятно в чем дело. Спасибо за исус!
